/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_26 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] result,
    output reg [0:0] z,
    output reg [0:0] v,
    output reg [0:0] n
  );
  
  
  
  reg [15:0] aOPb;
  
  reg [7:0] xb;
  
  integer i;
  
  always @* begin
    if (alufn != 6'h02) begin
      for (i = 1'h0; i < 4'h8; i = i + 1) begin
        xb[(i)*1+0-:1] = b[(i)*1+0-:1] ^ alufn[0+0-:1];
      end
      aOPb = a + xb + alufn[0+0-:1];
      v = (a[7+0-:1] & xb[7+0-:1] & ~aOPb[7+0-:1]) | (~a[7+0-:1] & ~xb[7+0-:1] & aOPb[7+0-:1]);
    end else begin
      aOPb = a * b;
      v = (|aOPb[8+7-:8] | (~a[7+0-:1] & ~b[7+0-:1] & aOPb[7+0-:1]));
    end
    result = aOPb[0+7-:8];
    z = (~|aOPb[0+7-:8]);
    n = aOPb[7+0-:1];
  end
endmodule
